version: '3.8'

services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chroma-server
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - CHROMA_SERVER_AUTH_PROVIDER=${CHROMA_SERVER_AUTH_PROVIDER:-chromadb.auth.token_authn.TokenAuthenticationServerProvider}
      - CHROMA_SERVER_AUTH_CREDENTIALS=${CHROMA_SERVER_AUTH_CREDENTIALS:-test-token}
      - CHROMA_PERSIST_DIRECTORY=/chroma/chroma
    networks:
      - chroma-network
    restart: unless-stopped

volumes:
  chroma_data:
    driver: local

networks:
  chroma-network:
    driver: bridge