version: '3.8'

services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chroma-server
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - CHROMA_SERVER_AUTH_PROVIDER=${CHROMA_SERVER_AUTH_PROVIDER:-chromadb.auth.token_authn.TokenAuthenticationServerProvider}
      - CHROMA_SERVER_AUTH_CREDENTIALS=${CHROMA_SERVER_AUTH_CREDENTIALS:-test-token}
      - CHROMA_PERSIST_DIRECTORY=/chroma/chroma
    networks:
      - chroma-network
    restart: unless-stopped

  chroma-admin:
    image: fengzhichao/chromadb-admin:latest
    container_name: chroma-admin
    ports:
      - "3001:3001"
    environment:
      - CHROMA_API_URL=http://host.docker.internal:8000
    depends_on:
      - chromadb
    networks:
      - chroma-network
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  chroma_data:
    driver: local

networks:
  chroma-network:
    driver: bridge