/**
 * Auto-generated version information from package.json
 * Generated by scripts/generate-version.js
 * DO NOT EDIT THIS FILE DIRECTLY
 */

export const VERSION = '2.1.4';
export const PACKAGE_NAME = '@aaswe/42context-engine';
export const PACKAGE_DESCRIPTION = 'AI-powered code search ';
