#!/usr/bin/env node

/**
 * Build script to generate version information from package.json
 * This ensures version is available at runtime without file system lookups
 */

const { readFileSync, writeFileSync } = require('fs');
const { join } = require('path');

// Read package.json
const packageJsonPath = join(__dirname, '..', 'package.json');
const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf-8'));

// Generate version module
const versionModule = `/**
 * Auto-generated version information from package.json
 * Generated by scripts/generate-version.js
 * DO NOT EDIT THIS FILE DIRECTLY
 */

export const VERSION = '${packageJson.version}';
export const PACKAGE_NAME = '${packageJson.name}';
export const PACKAGE_DESCRIPTION = '${packageJson.description}';
`;

// Write version file
const versionFilePath = join(__dirname, '..', 'src', 'mcp', 'version-generated.ts');
writeFileSync(versionFilePath, versionModule);

console.log(`✅ Generated version file: ${versionFilePath}`);
console.log(`   Version: ${packageJson.version}`);
console.log(`   Package: ${packageJson.name}`);